version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bash -c "sleep 30 && bundle exec rails db:reset db:seed && bundle exec rails server -b 0.0.0.0"


    
  db:
    volumes:
        - ./data/db:/var/lib/postgresql/data
    image: postgres:15
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

